pipeline {
  agent any
 
  tools {
  maven 'MAVEN3'
  }
  stages {
    stage ('Build') {
      steps {
      sh 'mvn clean install -f MyWebApp/pom.xml'
      }
    }
    stage ('JaCoCo') {
      steps {
      jacoco()
      }
    }
    stage ('Dev Deploy') {
      steps {
      echo "deploying to DEV Env "
      deploy adapters: [tomcat9(credentialsId: '82328406-81a4-4f0c-b068-f314ea0a0f25', path: '', url: 'http://1ec2-3-17-182-5.us-east-2.compute.amazonaws.com:8080')], contextPath: null, war: '**/*.war'
      }
    } 
  }
}
